Update FindEven.yml

diff --git a/.github/workflows/FindEven.yml b/.github/workflows/FindEven.yml
--- a/.github/workflows/FindEven.yml
+++ b/.github/workflows/FindEven.yml
@@ -21,4 +21,11 @@ jobs:
 
       - name: File exists
         if: steps.check_files.outputs.files_exists == 'true'
-        run: echo All files exists!
+        run: |
+          line = wc -l < FindEven.md
+          if [$line%2 != 0]; then:
+            echo "fail"
+            exit 1
+          fi
+        
+       
